[package]
name = "rust_norem"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.3"
rustyline = "8.2.0"
rustyline-derive = "0.4.0"
lazy_static = "1.4.0"
libc = "0.2.98"
bimap = "0.6.1"
scopeguard = "1.1.0"
regex = "1.5.4"